name: Lint

on: [push, pull_request]

permissions:
    contents: read

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - name: Install dependencies
              run: npm ci
            - name: Prettier
              run: npm run prettier:check
            - name: ESLint
              if: success() || failure()
              run: npm exec eslint -- --max-warnings 0 --ignore-pattern docs/examples/ .
            - name: Stylelint
              if: success() || failure()
              run: npm run stylelint -- --max-warnings 0
            - name: Build
              run: npm run --if-present build
            - name: Lint examples
              run: npm exec eslint -- --max-warnings 0 docs/examples/

    npm-pkg-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
            - name: Install Dependencies
              run: npm ci
            - name: npm-pkg-lint
              uses: ext/npm-pkg-lint@master
              with:
                  allow-dependencies: "@babel/parser,@babel/traverse"
