name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - closed
jobs:
    deploy-docs-preview:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - name: Install and build
              if: github.event.action != 'closed'
              id: prerelease
              run: |
                  npm ci
                  npm run build
                  npm run build:docs
                  npm pack
                  mkdir -p ./temp/pr-preview/docs-generator
                  cp -r ./public/* ./temp/pr-preview/docs-generator
                  export VERSION=$(npm pkg get version | jq -r)
                  echo "{ \"versions\": [\"v${VERSION}\"], \"latest\": \"v${VERSION}\" }" | tee ./temp/pr-preview/versions.json
                  echo "version=${VERSION}" | tee -a $GITHUB_OUTPUT
                  echo "pkg=forsakringskassan-docs-generator-${VERSION}.tgz" | tee -a $GITHUB_OUTPUT
            - name: Clear node_modules
              run: rm -rf node_modules
            #FKUI
            - uses: actions/checkout@v4
              with:
                  path: "fkui"
                  repository: "Forsakringskassan/designsystem"
            - name: Build FKUI documentation
              if: github.event.action != 'closed'
              working-directory: ./fkui
              run: |
                  npm ci
                  npm install "${GITHUB_WORKSPACE}/${{ steps.prerelease.outputs.pkg }}"
                  npm install --workspaces "${GITHUB_WORKSPACE}/${{ steps.prerelease.outputs.pkg }}"
                  npm run build || true
                  npm run build:docs || true
                  mkdir -p ../temp/pr-preview/fkui/
                  cp -r ./public/* ../temp/pr-preview/fkui/ || true
                  cat << EOF > ../temp/pr-preview/index.html
                  <style>
                    body {
                      padding: 2rem;
                      font-family: sans-serif;
                    }
                    a {
                      background-color: #4a52b6;
                      text-decoration: none;
                      color: white;
                      margin-bottom: 1rem;
                      border-radius: 4px;
                      padding: 0.5rem;
                      display: inline-block;
                    }
                    a:hover {
                      background-color: #3b4292;
                    }
                  </style>
                  <a href="./docs-generator">FK Documentation generator</a>
                  <br>
                  <a href="./fkui">FK Designsystem</a>
                  EOF
            - name: Deploy docs
              uses: rossjrw/pr-preview-action@v1
              with:
                  source-dir: ./temp/pr-preview/
                  preview-branch: gh-pages
                  umbrella-dir: pr-preview
                  action: auto
