name: Deploy PR previews
concurrency: preview-${{ github.ref }}

on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - closed

permissions:
    contents: read

jobs:
    deploy-docs-preview:
        if: github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 24.x
            - name: Checkout public folder
              uses: actions/checkout@v6
            - name: Prepare public
              id: public
              run: |
                  rm -rf *
                  mkdir temp
                  echo "dir=${GITHUB_WORKSPACE}/temp" | tee -a $GITHUB_OUTPUT
            - name: Checkout Forsakringskassan/docs-generator
              uses: actions/checkout@v6
              with:
                  path: "./docs-generator"
            - name: Install and build
              if: github.event.action != 'closed'
              id: prerelease
              working-directory: ./docs-generator
              run: |
                  npm ci
                  npm run build
                  npm run build:docs
                  npm pack
                  mkdir -p "${{ steps.public.outputs.dir }}/docs-generator"
                  cp -r ./public/* "${{ steps.public.outputs.dir }}/docs-generator"
                  export VERSION=$(npm pkg get version | jq -r)
                  echo "{ \"versions\": [\"v${VERSION}\"], \"latest\": \"v${VERSION}\" }" | tee "${{ steps.public.outputs.dir }}/versions.json"
                  echo "version=${VERSION}" | tee -a $GITHUB_OUTPUT
                  echo "pkg=${GITHUB_WORKSPACE}/docs-generator/forsakringskassan-docs-generator-${VERSION}.tgz" | tee -a $GITHUB_OUTPUT
            - name: Checkout Forsakringskassan/designsystem
              uses: actions/checkout@v6
              with:
                  path: "./fkui"
                  repository: "Forsakringskassan/designsystem"
            - name: Build FKUI documentation
              if: github.event.action != 'closed'
              working-directory: ./fkui
              run: |
                  npm ci
                  npm install "${{ steps.prerelease.outputs.pkg }}"
                  npm install --workspaces "${{ steps.prerelease.outputs.pkg }}"
                  npm run build
                  npm run build:docs
                  mkdir -p "${{ steps.public.outputs.dir }}/fkui"
                  cp -r ./public/* "${{ steps.public.outputs.dir }}/fkui"
            - name: Create landing page
              if: github.event.action != 'closed'
              working-directory: ${{ steps.public.outputs.dir }}
              run: |
                  cat << EOF > index.html
                  <style>
                    body {
                      padding: 2rem;
                      font-family: sans-serif;
                    }
                    a {
                      background-color: #4a52b6;
                      text-decoration: none;
                      color: white;
                      margin-bottom: 1rem;
                      border-radius: 4px;
                      padding: 0.5rem;
                      display: inline-block;
                    }
                    a:hover {
                      background-color: #3b4292;
                    }
                  </style>
                  <a href="./docs-generator">FK Documentation generator</a>
                  <br>
                  <a href="./fkui">FK Designsystem</a>
                  EOF
            - name: Deploy docs
              uses: rossjrw/pr-preview-action@v1
              with:
                  source-dir: ${{ steps.public.outputs.dir }}
                  preview-branch: gh-pages
                  umbrella-dir: pr-preview
                  action: auto
